---
- name: Retrieving network information
  shell: ip -4 addr | grep global | awk -v OFS=',' '{print $2, $4, $8}'
  register: network_info

- name: Adding static ip configuration to /etc/dhcpcd.conf file
  blockinfile:
          path: /etc/dhcpcd.conf
          block: |
                  interface {{ item.split(',')[2] }}
                  static ip_address={{ item.split(',')[0] | regex_replace('[0-9]{1,3}\/[0-9]{1,3}$')  }}{% if 'eth' in item.split(',')[2] %}{{ ip_addr_ext }}{% else %}{{ ip_addr_ext + 1 }}{% endif %}/{{ item.split(',')[0] | regex_replace('^.*/') }}
                  static routers={{ item.split(',')[1] }}
                  static domain_name_servers={{ item.split(',')[1] }}
          marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.split(',')[2] }}"
  with_items: "{{ network_info.stdout_lines }}"
  become_user: root
  become: true
